# MinecraftMCP Configuration

# MCP Server settings
mcp-server:
  # Enable or disable the MCP server
  enabled: true
  # Protocol settings - http only
  transport: http
  # HTTP transport settings
  http:
    # HTTP port for the MCP server
    port: 25575
    # Endpoint prefix for MCP API
    endpoint: "/mcp"
    # Enable or disable SSE streaming for MCP communication
    sse-enabled: true
    # Maximum number of SSE connections allowed (increased for Claude Desktop)
    max-connections: 20
    # Cross-Origin Resource Sharing (CORS) settings
    cors:
      # Enable or disable CORS
      enabled: false
      # Allowed origins (* for all, or specific domains)
      allowed-origins: "*"
    # Access logging
    access-logging: false
  
# Security settings
security:
  # Authentication settings
  authentication:
    # Enable API key authentication
    api-key-enabled: true
    # API key for MCP authentication (change this to a secure value)
    api-key: "change-this-to-a-secure-value"
    # Allow connections only from localhost (127.0.0.1)
    localhost-only: false
    # Session timeout in minutes (0 = never)
    session-timeout: 30
  
  # Command whitelisting
  command-whitelist:
    # Enable command whitelisting
    enabled: true
    # List of allowed commands (supports wildcards with *)
    allowed-commands:
      - "list"
      - "say"
      - "tp"
      - "kick"
      - "ban"
      - "pardon"
      - "op"
      - "deop"
      - "gamemode"
      - "time"
      - "weather"
      - "difficulty"
  
  # Rate limiting settings
  rate-limiting:
    # Enable rate limiting
    enabled: true
    # Maximum number of commands per minute (increased for Claude Desktop)
    commands-per-minute: 300
    # Maximum number of failed authentication attempts before temporary ban (increased for Claude Desktop)
    max-auth-attempts: 50
    # Temporary ban duration in minutes (reduced for faster recovery)
    temp-ban-duration: 5

# Debug settings (temporarily enabled to monitor Claude Desktop usage)
debug:
  enabled: true
  log-level: INFO

# Feature toggles
features:
  # Enable player tracking through MCP
  player-tracking: true
  # Enable world manipulation through MCP
  world-manipulation: true
  # Enable inventory manipulation through MCP
  inventory-manipulation: true

# MCP Capabilities
capabilities:
  # Enable MCP tools
  tools: true
  # Enable MCP resources
  resources: true
  # Enable MCP prompts
  prompts: true
  # Enable logging through MCP
  logging: true